### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Zlud** [ManavvGarg/Discord-Moderation-Bot#44]
Error: Cannot find module 'C:\Users\Evoon\Desktop\Discord bot\main.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []

**Comment by beznac** [comment]
I have the same issue. I wonder what the fix is.

**Comment by ManavvGarg** [comment]
This probably occurred at your end. As I am using the same (code from this github repo) and it is working fine. 
This might have occurred because you have changed the files' name. 

Make sure to keep the main file where you have initialized the bot, "index.js"
