### ISSUE TITLE
Unable to do npm i and error when i run node index.js

### ISSUE THREAD

**Issue by KlaasNiphaas** [ManavvGarg/Discord-Moderation-Bot#48]
I use Visual Studio Code i edited all the things that are supposed to be edited and this is what i get:

Error Log in files
https://sourceb.in/j2QHZP80Xo

Error Log in terminal when running npm i
https://sourceb.in/1Vtk6qxOa1

Error Log in terminal when running node index.js
https://sourceb.in/x2m3rw0SU6

**Comment by potatoman42o** [comment]
same issue

**Comment by ThatBoiSimple** [comment]
> I use Visual Studio Code i edited all the things that are supposed to be edited and this is what i get:
> 
> Error Log in files
> https://sourceb.in/j2QHZP80Xo
> 
> Error Log in terminal when running npm i
> https://sourceb.in/1Vtk6qxOa1
> 
> Error Log in terminal when running node index.js
> https://sourceb.in/x2m3rw0SU6

You need to have python installed.
In the logs when u did npm i it said

`
 **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
`

**Comment by ManavvGarg** [comment]
You need python to install and parse quick.db package
Make sure to have python installed. By looking at your console errors, it is clear that you dont have python 
installed.
![image](https://user-images.githubusercontent.com/58691392/113500899-5404a180-953f-11eb-95f0-86370e7baf40.png)

**Comment by Jxq7** [comment]
> You need python to install and parse quick.db package
> Make sure to have python installed. By looking at your console errors, it is clear that you dont have python
> installed.
> ![image](https://user-images.githubusercontent.com/58691392/113500899-5404a180-953f-11eb-95f0-86370e7baf40.png)
how do install quick.db in pythion? do i use pip install quick.db or whaat
